version: '3.8'

services:
  laravel:
    build:
      context: ./laravel-backend
      dockerfile: Dockerfile
    volumes:
      - ./laravel-backend:/var/www/html:cached
    ports:
      - "8095:8095"
    environment:
      - APP_ENV=local
    command: php artisan serve --host=0.0.0.0 --port=8095

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - node_modules:/app/node_modules
    ports:
      - "5174:5174"
    environment:
      - VITE_APP_URL=http://host.docker.internal:8095
      - VITE_API_URL=http://host.docker.internal:8095
    command: sh -c "npm ci --include=dev --silent || npm install --include=dev --silent; npm run dev -- --host 0.0.0.0 --port 5174"

volumes:
  node_modules:
    driver: local
