# Secrets para Panorama PMT
# Configurar en Streamlit Cloud o crear .streamlit/secrets.toml local

[general]
env = "prod"

[providers]
# Google Maps API Key para comparador de velocidades (futuro)
GOOGLE_MAPS_API_KEY = ""

[storage]
# Configuración de base de datos
DATABASE_URL = "sqlite:///./data/app.db"
sqlite_path = "data/app.sqlite"

[apps_script]
# URL base para Google Apps Script (sin parámetros específicos)
script_base_url = ""

[aforos]
# Configuración por defecto para equivalencias vehiculares
default_equivalencias = """
{
  "auto": 1.0,
  "camioneta": 1.0,
  "camion": 2.0,
  "bus": 2.5,
  "moto": 0.5,
  "bicicleta": 0.2,
  "peaton": 0.0
}
"""